package diag

import (
	"fmt"
	"time"
)

// GenerateReadme produces the human-readable README.md for the bundle root.
func GenerateReadme(ventdVersion, kernelVersion, redactorProfile, hostRedacted string, capturedAt time.Time) []byte {
	return fmt.Appendf(nil, `# ventd diagnostic bundle

Captured: %s
Hostname: [redacted to %s]
ventd version: %s
Kernel: %s
Schema version: ventd-diag-bundle-v1
Redaction profile: %s

## What ventd thought was happening

See: ./profile  (effective controller profile / config)
See: ./calibration  (current calibration result)

## What was actually on the wire (last events)

See: ./journal  (filtered systemd journal tail)

## Hardware ground truth

See: ./hwmon  (lm_sensors snapshot)
See: ./gpu    (PCI display devices)

## Redaction

This bundle was captured with the %q redaction profile.
See REDACTION_REPORT.json for what was changed.

## If you also have a system-wide issue

Consider also attaching: sos report --batch --clean

---
Generated by ventd %s
`,
		capturedAt.Format(time.RFC3339),
		hostRedacted,
		ventdVersion,
		kernelVersion,
		redactorProfile,
		redactorProfile,
		ventdVersion,
	)
}
