name: Feature request
description: Something ventd should do that it doesn't.
title: "[feat] "
labels: ["feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What are you trying to do that ventd doesn't support?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: What would a solution look like?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What have you tried / looked at?
