package detectors

import (
	"context"
	"errors"
	"strings"
	"testing"

	"github.com/ventd/ventd/internal/doctor"
)

// stubModulesFS is a minimal in-memory ModulesLoadFS for tests.
type stubModulesFS struct {
	files map[string][]byte
	err   error // returned for any path not in files when err != nil
}

func (s *stubModulesFS) ReadFile(name string) ([]byte, error) {
	if data, ok := s.files[name]; ok {
		return data, nil
	}
	if s.err != nil {
		return nil, s.err
	}
	return nil, errFileNotExist // emulate os.IsNotExist behaviour
}

// errFileNotExist mimics the os.IsNotExist signal that real os.ReadFile
// returns; we match the message that isNotExistErr looks for.
var errFileNotExist = errors.New("open /fake/path: no such file or directory")

func TestRULE_DOCTOR_DETECTOR_ModulesLoad_AllPresentAndCorrect(t *testing.T) {
	files := map[string][]byte{
		modulesLoadConfPath("nct6687"):     []byte("nct6687\n"),
		modulesLoadConfPath("corsair-cpro"): []byte("# auto-generated by ventd\ncorsair-cpro\n"),
	}
	det := NewModulesLoadDetector([]string{"nct6687", "corsair-cpro"}, &stubModulesFS{files: files})

	facts, err := det.Probe(context.Background(), doctor.Deps{Now: fixedNow})
	if err != nil {
		t.Fatalf("Probe: %v", err)
	}
	if len(facts) != 0 {
		t.Errorf("happy path emitted facts: %+v", facts)
	}
}

func TestRULE_DOCTOR_DETECTOR_ModulesLoad_MissingFileSurfacesAsWarning(t *testing.T) {
	det := NewModulesLoadDetector([]string{"nct6687"}, &stubModulesFS{})

	facts, err := det.Probe(context.Background(), doctor.Deps{Now: fixedNow})
	if err != nil {
		t.Fatalf("Probe: %v", err)
	}
	if len(facts) != 1 {
		t.Fatalf("expected 1 fact for missing drop-in, got %d", len(facts))
	}
	f := facts[0]
	if f.Severity != doctor.SeverityWarning {
		t.Errorf("Severity = %v, want Warning (live module is loaded)", f.Severity)
	}
	if !strings.Contains(f.Title, "missing") {
		t.Errorf("Title doesn't say missing: %q", f.Title)
	}
}

func TestRULE_DOCTOR_DETECTOR_ModulesLoad_DriftedContentSurfacesAsWarning(t *testing.T) {
	files := map[string][]byte{
		modulesLoadConfPath("nct6687"): []byte("# operator removed the module name\n# nct6687 was here\n"),
	}
	det := NewModulesLoadDetector([]string{"nct6687"}, &stubModulesFS{files: files})

	facts, _ := det.Probe(context.Background(), doctor.Deps{Now: fixedNow})
	if len(facts) != 1 {
		t.Fatalf("expected 1 fact for drifted content, got %d (%+v)", len(facts), facts)
	}
	if !strings.Contains(facts[0].Title, "no longer references") {
		t.Errorf("Title doesn't say drifted: %q", facts[0].Title)
	}
}

func TestRULE_DOCTOR_DETECTOR_ModulesLoad_PermissionDeniedSurfaces(t *testing.T) {
	det := NewModulesLoadDetector([]string{"nct6687"}, &stubModulesFS{
		err: errors.New("permission denied"),
	})

	facts, _ := det.Probe(context.Background(), doctor.Deps{Now: fixedNow})
	if len(facts) != 1 {
		t.Fatalf("expected 1 fact for permission-denied, got %d", len(facts))
	}
	if !strings.Contains(facts[0].Title, "Cannot verify") {
		t.Errorf("Title doesn't say cannot-verify: %q", facts[0].Title)
	}
}

func TestRULE_DOCTOR_DETECTOR_ModulesLoad_RespectsContextCancel(t *testing.T) {
	det := NewModulesLoadDetector([]string{"nct6687"}, &stubModulesFS{})
	ctx, cancel := context.WithCancel(context.Background())
	cancel()

	_, err := det.Probe(ctx, doctor.Deps{Now: fixedNow})
	if err == nil {
		t.Errorf("Probe on cancelled ctx returned nil err")
	}
}

func TestContentMentionsModule_SubstringNotFalseMatch(t *testing.T) {
	// "nct6687d" must not match "nct6687" — token-bounded only.
	if contentMentionsModule([]byte("nct6687d\n"), "nct6687") {
		t.Errorf("substring match on different module name")
	}
	// Explicit positive: a comment line doesn't count.
	if contentMentionsModule([]byte("# nct6687 comment only\n"), "nct6687") {
		t.Errorf("comment line treated as content")
	}
	// Whitespace + comma fields both work.
	if !contentMentionsModule([]byte("nct6687\n"), "nct6687") {
		t.Errorf("simple match failed")
	}
	if !contentMentionsModule([]byte("nct6687, corsair-cpro\n"), "corsair-cpro") {
		t.Errorf("comma-separated list match failed")
	}
}

func TestModulesLoadConfPath_FormatStable(t *testing.T) {
	got := modulesLoadConfPath("nct6687")
	want := "/etc/modules-load.d/ventd-nct6687.conf"
	if got != want {
		t.Errorf("modulesLoadConfPath = %q, want %q", got, want)
	}
}
