// SPDX-License-Identifier: GPL-3.0-or-later
package lmsensors

import (
	"fmt"
	"io"
	"sort"
	"strings"
)

// EmitOverlay writes a ventd hwdb chip-overlay YAML document to w
// for each ChipBlock that produced at least one label or ignore
// entry. Empty blocks are skipped — emitting a chip stanza with no
// content would be ghost data.
//
// The output is a YAML document of the shape:
//
//	# Generated by `ventd import-sensors-conf <path>` — DO NOT EDIT.
//	# Source: <input path>
//	# Re-run the importer when the upstream sensors.conf updates.
//	schema_version: "1.3"
//	chip_overlays:
//	  - patterns: [<pattern1>, <pattern2>]
//	    sensor_labels:
//	      <input>: <label>
//	    sensor_ignore:
//	      - <input>
//
// The chip_overlays shape is forward-compat: the hwdb v1.3 schema
// reserves `sensor_labels` + `sensor_ignore` as optional fields on
// chip profiles. The importer's output lands in
// /var/lib/ventd/profiles-pending/ and is reviewed by the operator
// before promotion into the live catalog (per the existing
// RULE-HWDB-CAPTURE-01 capture flow).
//
// Output is deterministic: chip patterns are stable across runs,
// labels and ignores within a block are emitted in sorted order so
// a re-import of the same input produces a byte-identical overlay.
func EmitOverlay(w io.Writer, sourcePath string, blocks []ChipBlock) error {
	if _, err := fmt.Fprintf(w, "# SPDX-License-Identifier: GPL-3.0-or-later\n"); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(w, "# Generated by `ventd import-sensors-conf %s` — DO NOT EDIT.\n", sourcePath); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(w, "# Re-run the importer when the upstream sensors.conf updates.\n"); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(w, "schema_version: \"1.3\"\n"); err != nil {
		return err
	}

	// Count non-empty blocks first so we emit the list header only
	// when there's content.
	nonEmpty := 0
	for _, b := range blocks {
		if len(b.Labels) == 0 && len(b.Ignored) == 0 {
			continue
		}
		nonEmpty++
	}
	if nonEmpty == 0 {
		// No actionable content — emit a comment so the operator
		// knows the import ran but had nothing to write.
		_, err := fmt.Fprintln(w, "# (no chip blocks with labels or ignores; overlay is empty)")
		return err
	}

	if _, err := fmt.Fprintln(w, "chip_overlays:"); err != nil {
		return err
	}
	for _, b := range blocks {
		if len(b.Labels) == 0 && len(b.Ignored) == 0 {
			continue
		}
		// patterns: ["pat1", "pat2"]
		var quotedPatterns []string
		for _, p := range b.Patterns {
			quotedPatterns = append(quotedPatterns, fmt.Sprintf("%q", p))
		}
		if _, err := fmt.Fprintf(w, "  - patterns: [%s]\n", strings.Join(quotedPatterns, ", ")); err != nil {
			return err
		}
		if len(b.Labels) > 0 {
			if _, err := fmt.Fprintln(w, "    sensor_labels:"); err != nil {
				return err
			}
			keys := make([]string, 0, len(b.Labels))
			for k := range b.Labels {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				if _, err := fmt.Fprintf(w, "      %s: %q\n", k, b.Labels[k]); err != nil {
					return err
				}
			}
		}
		if len(b.Ignored) > 0 {
			if _, err := fmt.Fprintln(w, "    sensor_ignore:"); err != nil {
				return err
			}
			keys := make([]string, 0, len(b.Ignored))
			for k := range b.Ignored {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				if _, err := fmt.Fprintf(w, "      - %s\n", k); err != nil {
					return err
				}
			}
		}
	}
	return nil
}
