#!/usr/bin/env python3
"""Generate internal/hal/msiec/firmware_catalogue.go from msi-ec.c."""
import re
import sys

src = open("/tmp/msi-ec.c").read()
pat = re.compile(
    r'static\s+const\s+char\s+\*ALLOWED_FW_(G[0-9_]+)\[\][^=]*=\s*\{([^}]*)\}\s*;',
    re.DOTALL,
)
groups = {}
order = []
for m in pat.finditer(src):
    name = m.group(1)
    body = m.group(2)
    fws = re.findall(r'"([^"]+)"', body)
    groups[name] = fws
    if name not in order:
        order.append(name)

header = '''// SPDX-License-Identifier: GPL-3.0-or-later

// Code generated by tools/gen-msiec-firmware-catalogue. DO NOT EDIT.
//
// Source: github.com/BeardOverflow/msi-ec  msi-ec.c  ALLOWED_FW_G*
//   tables. The driver groups firmware-version strings by their EC
//   register map (CONF_G1_0 .. CONF_G2_*) and accepts a load only when
//   the EC's reported firmware string is in the group's allowlist.
//
// ventd uses this catalogue to suggest closest-match firmware pins
// when an operator's actual firmware string is not in any allowlist —
// see firmware_diagnose.go. Pins are written to
// /etc/modprobe.d/ventd-msiec-firmware-pin.conf and the module is
// reloaded; the driver then maps the live (un-catalogued) firmware to
// the closest documented register layout.

package msiec

// FirmwareGroup names one of msi-ec's CONF_G* register-map groups and
// lists the firmware-version strings the upstream driver explicitly
// catalogues for it. The first firmware in each group is treated as
// the canonical representative for that group (used in
// SuggestFirmwarePins ranking).
type FirmwareGroup struct {
\tName      string
\tFirmwares []string
}

// firmwareGroups is the full ALLOWED_FW_G* catalogue extracted from
// the upstream msi-ec.c. Order matches the source file so reviewers
// can diff against upstream when re-generating.
var firmwareGroups = []FirmwareGroup{
'''

lines = [header]
for g in order:
    fws = groups[g]
    lines.append(f'\t{{Name: "CONF_{g}", Firmwares: []string{{\n')
    for f in fws:
        # Go quoted string
        f_esc = f.replace('\\', '\\\\').replace('"', '\\"')
        lines.append(f'\t\t"{f_esc}",\n')
    lines.append('\t}},\n')
lines.append('}\n')

sys.stdout.write(''.join(lines))
sys.stderr.write(f"groups={len(order)} firmwares={sum(len(groups[g]) for g in order)}\n")
