package config

import (
	"crypto/tls"
	"fmt"
	"log/slog"
	"math"
	"os"
	"path/filepath"
)

// tlsMigrationFSFn returns the filesystem pair (cert bytes, key bytes, load func)
// used by MigrateTLSPaths when probing the on-disk cert+key. Package-level so
// tests can redirect it without touching the live filesystem. Exposed through
// SetTLSMigrationFS; tests restore via t.Cleanup.
var tlsMigrationFSFn = defaultTLSMigrationFS

// defaultTLSMigrationFS reads bytes via os.ReadFile and parses via
// crypto/tls.X509KeyPair. Split out so tests can inject fake readers.
func defaultTLSMigrationFS(certPath, keyPath string) (certBytes, keyBytes []byte, parseErr error) {
	certBytes, err := os.ReadFile(certPath)
	if err != nil {
		return nil, nil, err
	}
	keyBytes, err = os.ReadFile(keyPath)
	if err != nil {
		return nil, nil, err
	}
	if _, err := tls.X509KeyPair(certBytes, keyBytes); err != nil {
		return certBytes, keyBytes, err
	}
	return certBytes, keyBytes, nil
}

// SetTLSMigrationFS replaces the reader/validator used by MigrateTLSPaths
// and returns the previous value so tests can restore it via t.Cleanup.
// Pass nil to restore the default.
func SetTLSMigrationFS(fn func(certPath, keyPath string) ([]byte, []byte, error)) func(certPath, keyPath string) ([]byte, []byte, error) {
	prev := tlsMigrationFSFn
	if fn == nil {
		tlsMigrationFSFn = defaultTLSMigrationFS
	} else {
		tlsMigrationFSFn = fn
	}
	return prev
}

// Migrate applies one-shot, backwards-compatible repairs to cfg in place.
// It returns true if cfg was mutated (callers then persist via Save), and
// an error only for conditions the operator must fix (never for "nothing
// to do").
//
// configPath is the path the cfg was loaded from; its directory is used
// as the search root for sibling artefacts generated by earlier ventd
// versions (e.g. a first-boot self-signed TLS pair).
//
// Currently covers one migration:
//
//   - TLS paths. PR #5's first-boot flow generated a self-signed
//     certificate+key at <configDir>/tls.crt and tls.key and set the
//     corresponding web.tls_cert / web.tls_key fields in the in-memory
//     cfg, but pre-F3 Save paths dropped those fields on serialisation.
//     A post-F2 daemon with PR #5's RequireTransportSecurity enabled
//     then refuses to start ("plaintext HTTP on 0.0.0.0:9999") even
//     though a valid keypair is already on disk. When both files exist
//     and parse as a keypair, repopulate the config fields so the
//     daemon starts clean and future saves preserve the reference.
//
// Migrations that cannot complete (e.g. one of the two TLS files is
// missing, the pair doesn't parse, a partial TLSCert/TLSKey is already
// set by the operator) are silent no-ops: Migrate preserves the cfg
// it was handed and returns mutated=false. The downstream transport-
// security check still runs with the unchanged cfg and produces its
// standard remediation message if plaintext-LAN is the net effect.
func Migrate(cfg *Config, configPath string, logger *slog.Logger) (mutated bool, err error) {
	if cfg == nil {
		return false, nil
	}
	if logger == nil {
		logger = slog.Default()
	}

	mutated = migrateTLSPaths(cfg, configPath, logger) || mutated

	return mutated, nil
}

// migrateTLSPaths is the one migration rule documented on Migrate. Kept
// separate so future migrations can land as sibling helpers without
// turning Migrate into a god function.
func migrateTLSPaths(cfg *Config, configPath string, logger *slog.Logger) bool {
	// Never overwrite an operator-authored value. If exactly one of the
	// two is set we also skip — half a keypair reference is almost
	// certainly a hand-edited footgun the daemon should surface via
	// its usual validation rather than silently "fix".
	if cfg.Web.TLSCert != "" || cfg.Web.TLSKey != "" {
		return false
	}

	dir := filepath.Dir(configPath)
	certPath := filepath.Join(dir, "tls.crt")
	keyPath := filepath.Join(dir, "tls.key")

	_, _, err := tlsMigrationFSFn(certPath, keyPath)
	if err != nil {
		// Every error path here is a "nothing to migrate" signal:
		//   - os.IsNotExist: either or both files absent — common
		//   - permission denied: rarer, but still "caller cannot
		//     validate the pair", so don't claim the fields
		//   - X509KeyPair parse error: the on-disk pair is malformed
		//     or expired; better to let the transport-security guard
		//     point the operator at the real problem than to paper
		//     over it by claiming a broken keypair works.
		return false
	}

	cfg.Web.TLSCert = certPath
	cfg.Web.TLSKey = keyPath
	logger.Info("config: migrated TLS paths from sibling files",
		"cert", certPath,
		"key", keyPath,
		"source", fmt.Sprintf("first-boot artefact next to %s", configPath),
	)
	return true
}

// MigrateCurvePWMFields reconciles the raw (0-255) and percent (0-100)
// duty-cycle fields on every curve and curve-point. The `_pct` form is
// the authoritative persistence shape; raw fields stay populated for
// runtime consumers (buildCurve, validate) that have always read them.
//
// Precedence: if both sides are set and disagree, `_pct` wins and a
// warning fires; otherwise the missing side is computed from the one
// that was set. A fresh config (both zero / nil on every field)
// round-trips through here without emitting any warning — the `_pct`
// sides end up as non-nil pointers to zero, which is distinguishable
// from nil via the YAML `omitempty` rule but prints the same to an
// operator.
//
// The conversion rounds: rawToPct(rawToPct⁻¹(x)) can differ from x
// by 1. That's fine for fan behaviour (±1 PWM is indistinguishable
// from motor noise) but tests that migrate a legacy value must
// compare against the round-tripped number, not the original.
func MigrateCurvePWMFields(cfg *Config) {
	if cfg == nil {
		return
	}
	for i := range cfg.Curves {
		c := &cfg.Curves[i]
		reconcile("curve "+c.Name+" min_pwm", &c.MinPWM, &c.MinPWMPct)
		reconcile("curve "+c.Name+" max_pwm", &c.MaxPWM, &c.MaxPWMPct)
		// Value is fixed-curve specific; still reconcile so other
		// curve types (which leave both at zero) emit a benign
		// `value_pct: 0` that round-trips.
		reconcile("curve "+c.Name+" value", &c.Value, &c.ValuePct)
		for j := range c.Points {
			p := &c.Points[j]
			reconcile(fmt.Sprintf("curve %s points[%d]", c.Name, j), &p.PWM, &p.PWMPct)
		}
	}
}

// reconcile is the per-field body of MigrateCurvePWMFields. label is
// an operator-facing identifier used in the "both set and disagree"
// warning.
//
// When both fields are populated, reconcile tolerates a ±1 round-trip
// drift (pctToRaw(rawToPct(x)) can differ from x by 1 due to the
// 255/100 scaling). A drift inside that tolerance is treated as "in
// sync": the raw side wins so successive calls to MigrateCurvePWMFields
// are idempotent. Only larger disagreements fire a warning.
func reconcile(label string, raw *uint8, pct **uint8) {
	if raw == nil || pct == nil {
		return
	}
	if *pct != nil {
		expected := pctToRaw(**pct)
		drift := int(*raw) - int(expected)
		if drift < 0 {
			drift = -drift
		}
		if *raw != 0 && drift > 1 {
			slog.Default().Warn("config: legacy and _pct fields disagree, preferring _pct",
				"field", label,
				"raw", *raw,
				"pct", **pct,
				"raw_from_pct", expected,
			)
			*raw = expected
			return
		}
		// Inside the ±1 rounding tolerance (or raw is the fresh zero we
		// haven't migrated yet): keep raw as it is if non-zero, else
		// populate it from pct.
		if *raw == 0 {
			*raw = expected
		}
		return
	}
	// _pct is nil; derive it from raw. rawToPct on zero is zero — the
	// fresh-config case produces ptr(0), which marshals as
	// `field_pct: 0` and reloads as the same.
	v := rawToPct(*raw)
	*pct = &v
}

// pctToRaw converts a 0-100 percent duty cycle to a 0-255 PWM byte.
// Clamps above 100; preserves the canonical zero.
func pctToRaw(pct uint8) uint8 {
	if pct > 100 {
		pct = 100
	}
	return uint8(math.Round(float64(pct) * 255 / 100))
}

// rawToPct converts a 0-255 PWM byte to a 0-100 percent duty cycle.
func rawToPct(raw uint8) uint8 {
	return uint8(math.Round(float64(raw) * 100 / 255))
}
