package config

import (
	"crypto/tls"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
)

// tlsMigrationFSFn returns the filesystem pair (cert bytes, key bytes, load func)
// used by MigrateTLSPaths when probing the on-disk cert+key. Package-level so
// tests can redirect it without touching the live filesystem. Exposed through
// SetTLSMigrationFS; tests restore via t.Cleanup.
var tlsMigrationFSFn = defaultTLSMigrationFS

// defaultTLSMigrationFS reads bytes via os.ReadFile and parses via
// crypto/tls.X509KeyPair. Split out so tests can inject fake readers.
func defaultTLSMigrationFS(certPath, keyPath string) (certBytes, keyBytes []byte, parseErr error) {
	certBytes, err := os.ReadFile(certPath)
	if err != nil {
		return nil, nil, err
	}
	keyBytes, err = os.ReadFile(keyPath)
	if err != nil {
		return nil, nil, err
	}
	if _, err := tls.X509KeyPair(certBytes, keyBytes); err != nil {
		return certBytes, keyBytes, err
	}
	return certBytes, keyBytes, nil
}

// SetTLSMigrationFS replaces the reader/validator used by MigrateTLSPaths
// and returns the previous value so tests can restore it via t.Cleanup.
// Pass nil to restore the default.
func SetTLSMigrationFS(fn func(certPath, keyPath string) ([]byte, []byte, error)) func(certPath, keyPath string) ([]byte, []byte, error) {
	prev := tlsMigrationFSFn
	if fn == nil {
		tlsMigrationFSFn = defaultTLSMigrationFS
	} else {
		tlsMigrationFSFn = fn
	}
	return prev
}

// Migrate applies one-shot, backwards-compatible repairs to cfg in place.
// It returns true if cfg was mutated (callers then persist via Save), and
// an error only for conditions the operator must fix (never for "nothing
// to do").
//
// configPath is the path the cfg was loaded from; its directory is used
// as the search root for sibling artefacts generated by earlier ventd
// versions (e.g. a first-boot self-signed TLS pair).
//
// Currently covers one migration:
//
//   - TLS paths. PR #5's first-boot flow generated a self-signed
//     certificate+key at <configDir>/tls.crt and tls.key and set the
//     corresponding web.tls_cert / web.tls_key fields in the in-memory
//     cfg, but pre-F3 Save paths dropped those fields on serialisation.
//     A post-F2 daemon with PR #5's RequireTransportSecurity enabled
//     then refuses to start ("plaintext HTTP on 0.0.0.0:9999") even
//     though a valid keypair is already on disk. When both files exist
//     and parse as a keypair, repopulate the config fields so the
//     daemon starts clean and future saves preserve the reference.
//
// Migrations that cannot complete (e.g. one of the two TLS files is
// missing, the pair doesn't parse, a partial TLSCert/TLSKey is already
// set by the operator) are silent no-ops: Migrate preserves the cfg
// it was handed and returns mutated=false. The downstream transport-
// security check still runs with the unchanged cfg and produces its
// standard remediation message if plaintext-LAN is the net effect.
func Migrate(cfg *Config, configPath string, logger *slog.Logger) (mutated bool, err error) {
	if cfg == nil {
		return false, nil
	}
	if logger == nil {
		logger = slog.Default()
	}

	mutated = migrateTLSPaths(cfg, configPath, logger) || mutated

	return mutated, nil
}

// migrateTLSPaths is the one migration rule documented on Migrate. Kept
// separate so future migrations can land as sibling helpers without
// turning Migrate into a god function.
func migrateTLSPaths(cfg *Config, configPath string, logger *slog.Logger) bool {
	// Never overwrite an operator-authored value. If exactly one of the
	// two is set we also skip — half a keypair reference is almost
	// certainly a hand-edited footgun the daemon should surface via
	// its usual validation rather than silently "fix".
	if cfg.Web.TLSCert != "" || cfg.Web.TLSKey != "" {
		return false
	}

	dir := filepath.Dir(configPath)
	certPath := filepath.Join(dir, "tls.crt")
	keyPath := filepath.Join(dir, "tls.key")

	_, _, err := tlsMigrationFSFn(certPath, keyPath)
	if err != nil {
		// Every error path here is a "nothing to migrate" signal:
		//   - os.IsNotExist: either or both files absent — common
		//   - permission denied: rarer, but still "caller cannot
		//     validate the pair", so don't claim the fields
		//   - X509KeyPair parse error: the on-disk pair is malformed
		//     or expired; better to let the transport-security guard
		//     point the operator at the real problem than to paper
		//     over it by claiming a broken keypair works.
		return false
	}

	cfg.Web.TLSCert = certPath
	cfg.Web.TLSKey = keyPath
	logger.Info("config: migrated TLS paths from sibling files",
		"cert", certPath,
		"key", keyPath,
		"source", fmt.Sprintf("first-boot artefact next to %s", configPath),
	)
	return true
}
