// calibration.js — v2 "command bridge" calibration takeover.
//
// Polls /api/v1/setup/status (1000ms) and /api/v1/status (800ms for live
// RPM). Renders the v2 layout (header / command bridge / scope / fan
// strips / system card / phase narrator / thermal preview / compute
// hero / done banner / error banner).
//
// Phase mapping: backend Progress.Phase is one of
//   detecting | installing_driver | scanning_fans | detecting_rpm | calibrating
// The two extra UI phases (probing_polarity, finalizing) are SYNTHESISED:
//   - probing_polarity: backend phase != calibrating AND any fan has
//     PolarityPhase == "testing"
//   - finalizing: backend phase == calibrating AND every viable fan has
//     CalPhase == "done"
//
// Per-fan PWM/RPM uses Progress.Fans[i].current_pwm / current_rpm
// directly during the calibrating phase (these are already populated by
// internal/setup/setup.go). Em-dashes are only shown in pending state.
//
// Demo mode (?demo=1, OR network failure to the API) drives every render
// function from synthetic state generated by the cal-state.js logic
// (translated inline below — same PHASES, FANS, FAN_RESULTS, T schedule).

(function () {
  'use strict';

  // ── theme toggle (dark default; localStorage override only) ─────────
  var root = document.documentElement;
  try {
    var stored = localStorage.getItem('ventd-theme');
    if (stored === 'light' || stored === 'dark') root.dataset.theme = stored;
  } catch (_) {}
  var themeBtn = document.getElementById('theme-toggle');
  if (themeBtn) themeBtn.addEventListener('click', function () {
    var next = root.dataset.theme === 'dark' ? 'light' : 'dark';
    root.dataset.theme = next;
    try { localStorage.setItem('ventd-theme', next); } catch (_) {}
  });

  // ── phase catalogue ─────────────────────────────────────────────────
  // Order matches the v2 pipeline; UI-only phases (probing_polarity,
  // finalizing) are synthesised client-side from per-fan state.
  var PHASES = [
    { id: 'detecting',         label: 'Detect chip',     short: 'Detecting',   blurb: 'Probing Super-IO and embedded controllers' },
    { id: 'installing_driver', label: 'Install driver',  short: 'Installing',  blurb: 'Compiling and inserting kernel module' },
    { id: 'scanning_fans',     label: 'Map channels',    short: 'Mapping',     blurb: 'Enumerating PWM channels and tach lines' },
    { id: 'detecting_rpm',     label: 'Pair tachs',      short: 'Pairing',     blurb: 'Matching each tach signal to its PWM driver' },
    { id: 'probing_polarity',  label: 'Probe polarity',  short: 'Polarity',    blurb: 'Verifying duty-cycle direction per channel' },
    { id: 'calibrating',       label: 'Sweep curves',    short: 'Calibrating', blurb: 'Sweeping each fan from min-spin to full-power' },
    { id: 'finalizing',        label: 'Compute curves',  short: 'Finalizing',  blurb: 'Solving thermal model — your fan curve is being written' }
  ];
  var PHASE_TITLES = {
    detecting:         'Probing system bus',
    installing_driver: 'Compiling kernel module',
    scanning_fans:     'Mapping PWM channels',
    detecting_rpm:     'Pairing tachometer signals',
    probing_polarity:  'Verifying duty-cycle polarity',
    calibrating:       'Sweeping fan response curves',
    finalizing:        'Solving thermal model',
    done:              'Calibration finished'
  };

  // ── cached element handles ──────────────────────────────────────────
  var $ = function (id) { return document.getElementById(id); };

  var els = {
    // header
    elapsed: $('cal-elapsed'),
    remaining: $('cal-remaining'),
    abort: $('cal-abort'),
    brandSub: $('cal-brand-sub'),
    // bridge
    phaseEyebrow: $('cal-phase-eyebrow'),
    phaseTitle: $('cal-phase-title'),
    phaseSub: $('cal-phase-sub'),
    bstatChannels: $('cal-bstat-channels'),
    bstatChannelsOf: $('cal-bstat-channels-of'),
    bstatSps: $('cal-bstat-sps'),
    bstatTotal: $('cal-bstat-total'),
    bstatFans: $('cal-bstat-fans'),
    bstatFansOf: $('cal-bstat-fans-of'),
    pipeline: $('cal-pipeline'),
    bridgeProgress: $('cal-bridge-progress'),
    // scope
    scopeMeta: $('cal-scope-meta'),
    scopeState: $('cal-scope-state'),
    scopeTx: $('cal-scope-tx'),
    scopeRx: $('cal-scope-rx'),
    sribStage: $('cal-srib-stage'),
    sribDuty: $('cal-srib-duty'),
    sribTach: $('cal-srib-tach'),
    sribAdc: $('cal-srib-adc'),
    sribSparkPath: $('cal-srib-spark-path'),
    // strips
    strips: $('cal-strips'),
    rosterViable: $('cal-roster-viable'),
    rosterMeta: $('cal-roster-meta'),
    // system
    sysBoard: $('cal-sys-board'),
    sysState: $('cal-sys-state'),
    sysRowChip: $('cal-sys-row-chip'),
    sysChip: $('cal-sys-chip'),
    sysRowDriver: $('cal-sys-row-driver'),
    sysDriver: $('cal-sys-driver'),
    sysRowCpu: $('cal-sys-row-cpu'),
    sysCpu: $('cal-sys-cpu'),
    sysRowGpu: $('cal-sys-row-gpu'),
    sysGpu: $('cal-sys-gpu'),
    sysRowFans: $('cal-sys-row-fans'),
    sysFans: $('cal-sys-fans'),
    sysRowTachs: $('cal-sys-row-tachs'),
    sysTachs: $('cal-sys-tachs'),
    // narrator
    narratorEyebrow: $('cal-narrator-eyebrow'),
    narratorTitle: $('cal-narrator-title'),
    narratorBlurb: $('cal-narrator-blurb'),
    narratorMsg: $('cal-narrator-msg'),
    // thermal
    thermal: $('cal-thermal'),
    thermalMeta: $('cal-thermal-meta'),
    thermalSvg: $('cal-thermal-svg'),
    thermalGrid: $('cal-thermal-grid'),
    thermalAxis: $('cal-thermal-axis'),
    thermalStopBand: $('cal-thermal-stop-band'),
    thermalStopLine: $('cal-thermal-stop-line'),
    thermalStopLabel: $('cal-thermal-stop-label'),
    thermalCurveBg: $('cal-thermal-curve-bg'),
    thermalCurve: $('cal-thermal-curve'),
    thermalAnchors: $('cal-thermal-anchors'),
    thermalMinSpin: $('cal-thermal-minspin'),
    thermalSlope: $('cal-thermal-slope'),
    thermalHeadroom: $('cal-thermal-headroom'),
    // compute
    compute: $('cal-compute'),
    computeTitle: $('cal-compute-title'),
    computeSub: $('cal-compute-sub'),
    computeIter: $('cal-compute-iter'),
    computeResidual: $('cal-compute-residual'),
    computeSvg: $('cal-compute-svg'),
    computeGrid: $('cal-compute-grid'),
    computeAxis: $('cal-compute-axis'),
    computeStopBand: $('cal-compute-stop-band'),
    computeStopLine: $('cal-compute-stop-line'),
    computeStopLabel: $('cal-compute-stop-label'),
    computeSamples: $('cal-compute-samples'),
    computeCurveArea: $('cal-compute-curve-area'),
    computeCurve: $('cal-compute-curve'),
    computeAnchors: $('cal-compute-anchors'),
    resultSamplesVal: $('cal-result-samples-val'),
    resultSamplesSub: $('cal-result-samples-sub'),
    resultResidualVal: $('cal-result-residual-val'),
    resultHeadroomVal: $('cal-result-headroom-val'),
    resultCurveVal: $('cal-result-curve-val'),
    computeSteps: $('cal-compute-steps'),
    // done
    doneBanner: $('cal-done-banner'),
    doneTitle: $('cal-done-title'),
    doneSub: $('cal-done-sub'),
    applyBtn: $('cal-apply-btn'),
    // error
    errorBanner: $('cal-error-banner'),
    errorSub: $('cal-error-sub'),
    retryBtn: $('cal-retry-btn'),
    skipBtn: $('cal-skip-btn'),
    bundleBtn: $('cal-bundle-btn'),
    bundleStatus: $('cal-bundle-status'),
    recoveryCards: $('cal-recovery-cards'),
    // modal
    modalOverlay: $('cal-modal-overlay'),
    modalTitle: $('cal-modal-title'),
    modalBody: $('cal-modal-body'),
    modalClose: $('cal-modal-close')
  };

  // ── small utilities ─────────────────────────────────────────────────
  function fmtClock(secs) {
    if (secs == null || !isFinite(secs) || secs < 0) return '—';
    var m = Math.floor(secs / 60), s = Math.floor(secs % 60);
    return (m < 10 ? '0' : '') + m + ':' + (s < 10 ? '0' : '') + s;
  }
  function clamp(v, lo, hi) { return Math.max(lo, Math.min(hi, v)); }
  function lerp(a, b, t) { return a + (b - a) * clamp(t, 0, 1); }
  function escapeHTML(s) {
    return String(s).replace(/[&<>"']/g, function (c) {
      return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c];
    });
  }
  function svgEl(tag, attrs) {
    var el = document.createElementNS('http://www.w3.org/2000/svg', tag);
    if (attrs) for (var k in attrs) el.setAttribute(k, attrs[k]);
    return el;
  }
  function shortPath(p) {
    if (!p) return '';
    return p.length > 28 ? '…' + p.slice(-28) : p;
  }

  // ── phase mapping (backend → UI) ────────────────────────────────────
  // Synthesise probing_polarity / finalizing client-side per the design
  // (backend Progress.Phase never emits these strings).
  function uiPhase(p) {
    if (!p) return 'detecting';
    if (p.applied) return 'done';
    if (p.done && !p.error) return 'done';
    var phase = p.phase || 'detecting';
    var fans = p.fans || [];
    // probing_polarity: any fan testing polarity AND backend not yet
    // calibrating
    if (phase !== 'calibrating' && phase !== 'finalizing' && phase !== 'done') {
      var anyTesting = false;
      for (var i = 0; i < fans.length; i++) {
        if (fans[i].polarity_phase === 'testing') { anyTesting = true; break; }
      }
      if (anyTesting) return 'probing_polarity';
    }
    // finalizing: backend says calibrating but every controllable fan
    // is done (or skipped/error) — i.e. nothing left to sweep
    if (phase === 'calibrating' && fans.length > 0) {
      var allDone = true, sweptOne = false;
      for (var j = 0; j < fans.length; j++) {
        var f = fans[j];
        if (f.cal_phase === 'done' || f.cal_phase === 'skipped' || f.cal_phase === 'error') {
          if (f.cal_phase === 'done') sweptOne = true;
          continue;
        }
        allDone = false;
        break;
      }
      if (allDone && sweptOne) return 'finalizing';
    }
    return phase;
  }

  // Pipeline + bridge update ------------------------------------------------
  function paintPipeline(currentPhase) {
    if (!els.pipeline) return;
    var idx = -1;
    for (var i = 0; i < PHASES.length; i++) if (PHASES[i].id === currentPhase) { idx = i; break; }
    var doneIdx = currentPhase === 'done' ? PHASES.length : idx;
    var nodes = els.pipeline.querySelectorAll('.v2-pipe-step');
    for (var k = 0; k < nodes.length; k++) {
      nodes[k].classList.remove('done', 'active', 'pending');
      if (k < doneIdx) nodes[k].classList.add('done');
      else if (k === idx) nodes[k].classList.add('active');
      else nodes[k].classList.add('pending');
    }
    var pct;
    if (currentPhase === 'done') pct = 100;
    else if (idx < 0) pct = 0;
    else pct = ((idx + 0.4) / PHASES.length) * 100;
    if (els.bridgeProgress) els.bridgeProgress.style.width = pct.toFixed(1) + '%';
  }

  function updateBridgeStats(p, currentPhase, sweepStats) {
    var fans = p.fans || [];
    var viable = 0, done = 0;
    for (var i = 0; i < fans.length; i++) {
      var f = fans[i];
      // a fan is "viable" if its detect_phase is found OR it's a non-hwmon
      // (NVML) channel that doesn't need a tach pairing.
      if (f.detect_phase === 'found' || f.detect_phase === 'n/a' || f.type === 'nvidia') viable++;
      if (f.cal_phase === 'done' || f.cal_phase === 'skipped') done++;
    }

    // Channels live: the count of fans with detect_phase advancing
    var live = 0;
    for (var l = 0; l < fans.length; l++) {
      if (fans[l].detect_phase && fans[l].detect_phase !== 'pending') live++;
    }

    // Samples / sec — derived heuristically from phase
    var sps = 0;
    if (currentPhase === 'scanning_fans')    sps = 800  + Math.round(Math.sin(Date.now() * 0.002) * 120);
    if (currentPhase === 'detecting_rpm')    sps = 2400 + Math.round(Math.sin(Date.now() * 0.0015) * 220);
    if (currentPhase === 'probing_polarity') sps = 1800 + Math.round(Math.sin(Date.now() * 0.0025) * 140);
    if (currentPhase === 'calibrating')      sps = 4200 + Math.round(Math.sin(Date.now() * 0.001) * 420);
    if (currentPhase === 'finalizing')       sps = 620  + Math.round(Math.sin(Date.now() * 0.003) * 60);

    if (els.bstatChannels)   els.bstatChannels.firstChild.nodeValue = live;
    if (els.bstatChannelsOf) els.bstatChannelsOf.textContent = '/' + Math.max(viable, 0);
    if (els.bstatSps)        els.bstatSps.textContent = sps.toLocaleString();
    if (els.bstatTotal && sweepStats) els.bstatTotal.textContent = sweepStats.totalSamples.toLocaleString();
    if (els.bstatFans)       els.bstatFans.firstChild.nodeValue = done;
    if (els.bstatFansOf)     els.bstatFansOf.textContent = '/' + fans.length;

    var phaseDef = PHASES.find(function (x) { return x.id === currentPhase; }) || { short: '—', blurb: '' };
    var phaseIdx = PHASES.findIndex(function (x) { return x.id === currentPhase; });
    var eyebrow = phaseIdx >= 0
      ? 'Phase ' + ('0' + (phaseIdx + 1)).slice(-2) + ' / 07 · ' + phaseDef.short
      : (currentPhase === 'done' ? 'Complete' : '—');
    if (els.phaseEyebrow) els.phaseEyebrow.textContent = eyebrow;
    if (els.phaseTitle)   els.phaseTitle.textContent = PHASE_TITLES[currentPhase] || (p.phase_msg || 'Calibrating');
    if (els.phaseSub)     els.phaseSub.textContent = phaseDef.blurb || (p.phase_msg || '');
  }

  // ── elapsed clock ───────────────────────────────────────────────────
  var startedAt = null;
  function tickClock(p) {
    if (!startedAt) startedAt = Date.now();
    var elapsed = Math.floor((Date.now() - startedAt) / 1000);
    if (els.elapsed) els.elapsed.textContent = fmtClock(elapsed);
    if (!els.remaining) return;
    var fans = p.fans || [];
    if (!fans.length) { els.remaining.innerHTML = '<span class="dim">—</span>'; return; }
    var done = 0;
    for (var i = 0; i < fans.length; i++) {
      if (fans[i].cal_phase === 'done' || fans[i].cal_phase === 'skipped') done++;
    }
    if (done === 0) { els.remaining.innerHTML = '<span class="dim">—</span>'; return; }
    var rate = elapsed / done;
    var remain = Math.max(0, Math.round(rate * (fans.length - done)));
    els.remaining.textContent = '~' + fmtClock(remain);
  }

  // ── fan strip rendering ─────────────────────────────────────────────
  function fanIconSVG() {
    return '<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">'
      + '<path d="M12 12 C 13 8, 14 5, 12 2 C 9 5, 10 8, 12 12 Z" opacity="0.85"/>'
      + '<path d="M12 12 C 16 11, 19 12, 22 10 C 19 8, 16 9, 12 12 Z" opacity="0.85"/>'
      + '<path d="M12 12 C 11 16, 10 19, 12 22 C 15 19, 14 16, 12 12 Z" opacity="0.85"/>'
      + '<path d="M12 12 C 8 13, 5 12, 2 14 C 5 16, 8 15, 12 12 Z" opacity="0.85"/>'
      + '<circle cx="12" cy="12" r="1.4" fill="currentColor"/>'
      + '</svg>';
  }

  function fanState(f) {
    // Map backend cal_phase + detect/polarity into UI strip state
    if (f.cal_phase === 'calibrating') return 'active';
    if (f.cal_phase === 'done')        return 'done';
    if (f.cal_phase === 'skipped')     return 'pending';
    if (f.cal_phase === 'error')       return 'pending';
    if (f.detect_phase === 'none')     return 'dropped';
    if (f.polarity_phase === 'phantom') return 'dropped';
    return 'pending';
  }

  function pillFor(f) {
    if (f.cal_phase === 'calibrating') return { cls: 'active',  label: 'Sweeping' };
    if (f.cal_phase === 'done')        return { cls: 'done',    label: 'Locked' };
    if (f.cal_phase === 'skipped')     return { cls: 'dropped', label: 'Skipped' };
    if (f.cal_phase === 'error')       return { cls: 'dropped', label: 'Error' };
    if (f.detect_phase === 'none')     return { cls: 'dropped', label: 'No tach' };
    if (f.polarity_phase === 'phantom') return { cls: 'dropped', label: 'Phantom' };
    if (f.polarity_phase === 'normal' || f.polarity_phase === 'inverted')
      return { cls: 'queued', label: 'Polarity ok' };
    if (f.detect_phase === 'found')    return { cls: 'queued', label: 'Paired' };
    if (f.detect_phase === 'detecting') return { cls: 'queued', label: 'Pairing' };
    return { cls: 'queued', label: 'Queued' };
  }

  function fanMessage(f) {
    if (f.cal_phase === 'done') {
      var bits = [];
      if (f.start_pwm != null) bits.push('start ' + f.start_pwm);
      if (f.stop_pwm != null)  bits.push('stop ' + f.stop_pwm);
      if (f.max_rpm)           bits.push(f.max_rpm + ' rpm');
      return bits.join(' · ');
    }
    if (f.cal_phase === 'calibrating') {
      var pct = Math.max(0, Math.min(100, f.cal_progress || 0));
      if (pct < 30) return 'seek min-spin · ' + (f.current_pwm || 0) + '%';
      if (pct < 86) return 'sweep · holding ' + (f.current_pwm || 0) + '%';
      return 'settle · solving slope';
    }
    if (f.cal_phase === 'error')    return f.error || 'error';
    if (f.cal_phase === 'skipped')  return 'no usable PWM range';
    if (f.detect_phase === 'none')  return 'no tach signal';
    if (f.polarity_phase === 'phantom') return 'no fan reacts';
    if (f.polarity_phase === 'inverted') return 'polarity: inverted';
    if (f.polarity_phase === 'normal')   return 'polarity: normal';
    if (f.polarity_phase === 'testing')  return 'probing polarity…';
    if (f.detect_phase === 'detecting')  return 'probing tach…';
    if (f.detect_phase === 'found')      return 'tach paired';
    return 'queued';
  }

  function renderStrips(p) {
    if (!els.strips) return;
    var fans = p.fans || [];
    if (!fans.length) {
      els.strips.innerHTML = '<div class="v2-strips-empty">Waiting for hardware scan…</div>';
      if (els.rosterViable) els.rosterViable.textContent = '0';
      if (els.rosterMeta)   els.rosterMeta.textContent = '0 of 0 resolved';
      return;
    }

    var done = 0, viable = 0;
    var html = '';
    for (var i = 0; i < fans.length; i++) {
      var f = fans[i];
      var state = fanState(f);
      var pill = pillFor(f);
      var msg = fanMessage(f);
      if (f.cal_phase === 'done' || f.cal_phase === 'skipped') done++;
      if (state !== 'dropped') viable++;

      // PWM / RPM display: prefer live current_pwm/current_rpm during
      // calibrating, fall back to em-dash for pending.
      var pwmDisp, rpmDisp, pwmPct, rpmPct;
      if (f.cal_phase === 'calibrating') {
        pwmDisp = f.current_pwm != null ? f.current_pwm : '—';
        rpmDisp = f.current_rpm != null ? f.current_rpm.toLocaleString() : '—';
        pwmPct = f.current_pwm != null ? (f.current_pwm / 255) * 100 : 0;
        rpmPct = f.current_rpm != null ? Math.min(100, (f.current_rpm / 30)) : 0;
      } else if (f.cal_phase === 'done') {
        pwmDisp = '100';
        rpmDisp = (f.max_rpm || 0).toLocaleString();
        pwmPct = 100;
        rpmPct = Math.min(100, (f.max_rpm || 0) / 30);
      } else {
        pwmDisp = '—'; rpmDisp = '—'; pwmPct = 0; rpmPct = 0;
      }

      var path = f.pwm_path ? shortPath(f.pwm_path) : (f.id || '');
      var kind = f.is_pump ? 'pump' : (f.type === 'nvidia' ? 'gpu' : 'fan');

      html += '<div class="v2-strip" data-state="' + state + '" data-fan-id="' + escapeHTML(f.pwm_path || f.id || ('f' + i)) + '">'
            +   '<div class="v2-strip-icon">' + fanIconSVG() + '</div>'
            +   '<div class="v2-strip-name">'
            +     '<div class="v2-strip-name-label">' + escapeHTML(f.name || '(fan)') + '</div>'
            +     '<div class="v2-strip-name-path"><span>' + escapeHTML(path) + '</span><span class="micro-pill">' + escapeHTML(kind) + '</span></div>'
            +   '</div>'
            +   '<div class="v2-strip-cell">'
            +     '<div class="v2-strip-cell-label">PWM</div>'
            +     '<div class="v2-strip-cell-val">' + escapeHTML(String(pwmDisp)) + (pwmDisp !== '—' ? '<small>%</small>' : '') + '</div>'
            +     '<div class="v2-strip-cell-bar"><div class="v2-strip-cell-bar-fill" data-w="' + pwmPct.toFixed(1) + '"></div></div>'
            +   '</div>'
            +   '<div class="v2-strip-cell">'
            +     '<div class="v2-strip-cell-label">RPM</div>'
            +     '<div class="v2-strip-cell-val rpm">' + escapeHTML(String(rpmDisp)) + '</div>'
            +     '<div class="v2-strip-cell-bar"><div class="v2-strip-cell-bar-fill" data-w="' + rpmPct.toFixed(1) + '"></div></div>'
            +   '</div>'
            +   '<div class="v2-strip-spark" data-spark-fan="' + escapeHTML(f.pwm_path || f.id || ('f' + i)) + '">'
            +     '<svg viewBox="0 0 100 32" preserveAspectRatio="none"><path d="" vector-effect="non-scaling-stroke"></path></svg>'
            +   '</div>'
            +   '<div class="v2-strip-status">'
            +     '<div class="v2-strip-pill ' + pill.cls + '">' + escapeHTML(pill.label) + '</div>'
            +     '<div class="v2-strip-msg">' + escapeHTML(msg) + '</div>'
            +   '</div>'
            + '</div>';
    }
    els.strips.innerHTML = html;

    // Apply bar widths from data-w attributes (CSP: no inline styles in
    // built HTML; element.style.width is fine via CSSOM).
    Array.prototype.forEach.call(
      els.strips.querySelectorAll('.v2-strip-cell-bar-fill[data-w]'),
      function (el) { el.style.width = el.dataset.w + '%'; }
    );

    // Update sparkline buffers + paint paths
    paintAllSparks(fans);

    if (els.rosterViable) els.rosterViable.textContent = viable;
    if (els.rosterMeta)   els.rosterMeta.textContent = done + ' of ' + fans.length + ' resolved';
  }

  // ── per-fan sparkline buffers ──────────────────────────────────────
  // Push current_rpm samples into a rolling buffer keyed by pwm_path so
  // each strip's mini chart stays alive during sweeps.
  var sparkBufs = {}; // pwm_path -> [number]
  var SPARK_LEN = 40;
  function pushSpark(key, v) {
    var buf = sparkBufs[key] || [];
    buf.push(v);
    if (buf.length > SPARK_LEN) buf.shift();
    sparkBufs[key] = buf;
    return buf;
  }
  function paintAllSparks(fans) {
    for (var i = 0; i < fans.length; i++) {
      var f = fans[i];
      var key = f.pwm_path || f.id || ('f' + i);
      var v;
      if (f.cal_phase === 'calibrating' && f.current_rpm != null) v = f.current_rpm;
      else if (f.cal_phase === 'done') v = f.max_rpm || 0;
      else v = 0;
      var buf = pushSpark(key, v);
      var path = els.strips ? els.strips.querySelector('[data-spark-fan="' + cssEsc(key) + '"] svg path') : null;
      if (!path) continue;
      if (buf.length < 2) { path.setAttribute('d', ''); continue; }
      var max = 1;
      for (var j = 0; j < buf.length; j++) if (buf[j] > max) max = buf[j];
      var d = '';
      for (var k = 0; k < buf.length; k++) {
        var x = (k / (SPARK_LEN - 1)) * 100;
        var y = 32 - (buf[k] / max) * 30;
        d += (k === 0 ? 'M ' : ' L ') + x.toFixed(1) + ' ' + y.toFixed(1);
      }
      path.setAttribute('d', d);
    }
  }
  function cssEsc(s) {
    return String(s).replace(/(["\\\/\#\?\&\[\]])/g, '\\$1');
  }

  // ── system card ─────────────────────────────────────────────────────
  function renderSystem(p) {
    if (els.sysBoard) els.sysBoard.textContent = p.board || 'Discovering…';
    if (els.sysState) {
      var ui = uiPhase(p);
      var lbl = ui === 'done' ? 'ready' : (p.applied ? 'applied' : 'calibrating');
      els.sysState.textContent = lbl;
      els.sysState.className = 'v2-pill ' + (ui === 'done' || p.applied ? 'ok' : 'info');
    }
    setSysRow(els.sysRowChip, els.sysChip,
      p.chip_name ? '<span class="mono">' + escapeHTML(p.chip_name) + '</span>' : '<span class="dim">probing super-io…</span>',
      !!p.chip_name);

    // Driver state derived from phase progression
    var ui = uiPhase(p);
    var driverState = 'pending', driverHTML = '<span class="dim">queued</span>';
    if (ui === 'installing_driver') driverHTML = '<span class="mono">building</span> <span class="v2-pill info">building</span>';
    else if (ui !== 'detecting' && ui !== 'pending') {
      driverState = 'found';
      driverHTML = '<span class="mono">' + escapeHTML(p.chip_name ? p.chip_name.toLowerCase() + '.ko' : 'driver') + '</span> <span class="v2-pill ok">loaded</span>';
    }
    setSysRow(els.sysRowDriver, els.sysDriver, driverHTML, driverState === 'found' || ui === 'installing_driver');

    var pr = p.profile || {};
    setSysRow(els.sysRowCpu, els.sysCpu,
      pr.cpu_model
        ? escapeHTML(pr.cpu_model) + (pr.cpu_tdp_w ? ' <span class="dim">· ' + pr.cpu_tdp_w + ' W</span>' : '')
        : '<span class="dim">—</span>',
      !!pr.cpu_model);
    setSysRow(els.sysRowGpu, els.sysGpu,
      pr.gpu_model
        ? escapeHTML(pr.gpu_model) + (pr.gpu_power_w ? ' <span class="dim">· ' + pr.gpu_power_w + ' W TGP</span>' : '')
        : '<span class="dim">—</span>',
      !!pr.gpu_model);

    var fans = p.fans || [];
    var paired = 0, total = fans.length, dropped = 0;
    for (var i = 0; i < fans.length; i++) {
      if (fans[i].detect_phase === 'found' || fans[i].detect_phase === 'n/a') paired++;
      if (fans[i].detect_phase === 'none' || fans[i].polarity_phase === 'phantom') dropped++;
    }
    var fansHTML;
    if (total === 0) fansHTML = '<span class="dim">scanning…</span>';
    else fansHTML = '<span class="mono">' + paired + '</span><span class="dim"> of </span><span class="mono">' + total + '</span>'
        + (dropped > 0 ? ' <span class="v2-pill warn">' + dropped + ' dropped</span>' : '');
    setSysRow(els.sysRowFans, els.sysFans, fansHTML, total > 0);

    setSysRow(els.sysRowTachs, els.sysTachs,
      paired > 0
        ? '<span class="mono">' + paired + '</span><span class="dim"> paired · 2 pulses/rev</span>'
        : '<span class="dim">—</span>',
      paired > 0);
  }
  function setSysRow(rowEl, valEl, html, found) {
    if (rowEl) rowEl.dataset.state = found ? 'found' : 'pending';
    if (valEl) valEl.innerHTML = html;
  }

  // ── phase narrator ──────────────────────────────────────────────────
  function renderNarrator(p, currentPhase) {
    var def = PHASES.find(function (x) { return x.id === currentPhase; });
    if (currentPhase === 'done') {
      def = { short: 'Complete', label: 'Done', blurb: 'All fans calibrated.' };
    }
    if (!def) def = PHASES[0];
    if (els.narratorEyebrow) els.narratorEyebrow.textContent = def.short;
    if (els.narratorTitle)   els.narratorTitle.textContent = PHASE_TITLES[currentPhase] || def.label;
    if (els.narratorBlurb)   els.narratorBlurb.textContent = def.blurb;
    if (els.narratorMsg)     els.narratorMsg.textContent = p.phase_msg || '';
  }

  // ── scope (decorative live signal) ──────────────────────────────────
  function paintScope(currentPhase) {
    if (!els.scopeTx || !els.scopeRx) return;
    var W = 800, H = 200;
    var t = Date.now();

    // TX trace — square pulse train, frequency varies by phase
    var hz = currentPhase === 'calibrating' ? 0.05 + 0.03 * Math.sin(t * 0.001) : 0.08;
    var pts = '';
    for (var x = 0; x <= W; x += 2) {
      var ph = (x * hz + t * 0.06) % 12;
      var y = ph < 5 ? H * 0.28 : H * 0.62;
      pts += (x === 0 ? 'M ' : ' L ') + x + ' ' + y.toFixed(1);
    }
    els.scopeTx.setAttribute('d', pts);

    // RX trace — narrower / lower amplitude (or noise floor pre-pairing)
    var rxPts = '';
    if (currentPhase === 'detecting' || currentPhase === 'installing_driver' || currentPhase === 'scanning_fans') {
      for (var x2 = 0; x2 <= W; x2 += 6) {
        var y2 = H * 0.78 + (Math.sin(x2 * 0.4 + t * 0.005) * 3);
        rxPts += (x2 === 0 ? 'M ' : ' L ') + x2 + ' ' + y2.toFixed(1);
      }
    } else {
      var rhz = currentPhase === 'calibrating' ? 0.09 + 0.06 * Math.sin(t * 0.0008) : 0.06;
      for (var x3 = 0; x3 <= W; x3 += 2) {
        var rph = (x3 * rhz + t * 0.04) % 14;
        var ry = rph < 2 ? H * 0.62 : H * 0.78;
        rxPts += (x3 === 0 ? 'M ' : ' L ') + x3 + ' ' + ry.toFixed(1);
      }
    }
    els.scopeRx.setAttribute('d', rxPts);

    // ribbon
    var stageMap = {
      detecting: 'super-io', installing_driver: 'kmod-build', scanning_fans: 'enum-pwm',
      detecting_rpm: 'tach-pair', probing_polarity: 'polarity', calibrating: 'sweep',
      finalizing: 'solver', done: 'idle'
    };
    if (els.sribStage)  els.sribStage.textContent = stageMap[currentPhase] || '—';
    if (els.scopeMeta)  els.scopeMeta.textContent = currentPhase === 'detecting' ? 'trace · 2-ch · noise floor' : 'trace · 2-ch · pwm/tach';
    if (els.scopeState) els.scopeState.textContent = currentPhase === 'done' ? 'IDLE' : 'CAPTURING';
    var hasPwm = !(currentPhase === 'detecting' || currentPhase === 'installing_driver');
    if (els.sribDuty) els.sribDuty.textContent = hasPwm ? '25 kHz' : '—';
    var hasTach = currentPhase === 'detecting_rpm' || currentPhase === 'probing_polarity'
               || currentPhase === 'calibrating' || currentPhase === 'finalizing';
    if (els.sribTach) els.sribTach.textContent = hasTach
      ? Math.round(20 + Math.abs(Math.sin(t * 0.002)) * 40) + ' Hz' : '—';
    if (els.sribAdc) els.sribAdc.textContent = hasPwm
      ? Math.round(220 + Math.sin(t * 0.004) * 40) + ' mV' : '—';

    // tiny spark
    if (els.sribSparkPath) {
      var sd = '';
      for (var i = 0; i < 28; i++) {
        var v = currentPhase === 'calibrating' ? 0.4 + 0.4 * Math.sin((t - i * 120) * 0.003)
              : currentPhase === 'finalizing'  ? 0.2 + 0.1 * Math.sin((t - i * 120) * 0.002)
              : 0.3 + 0.2 * Math.sin((t - i * 120) * 0.004);
        v = clamp(v, 0, 1);
        var sx = (i / 27) * 100, sy = (1 - v) * 14;
        sd += (i === 0 ? 'M ' : ' L ') + sx.toFixed(1) + ' ' + sy.toFixed(1);
      }
      els.sribSparkPath.setAttribute('d', sd);
    }
  }

  // ── thermal preview (smaller card) ──────────────────────────────────
  // Built from the first `done` fan's start/stop/max if available;
  // otherwise from a sensible default min-spin = 28%.
  function renderThermal(p, currentPhase) {
    if (!els.thermalSvg) return;
    var W = 360, H = 200;
    var padL = 32, padR = 16, padT = 14, padB = 26;
    var sx = function (x) { return padL + ((x - 20) / 75) * (W - padL - padR); };
    var sy = function (y) { return padT + (1 - y / 100) * (H - padT - padB); };

    // Pull a representative fan
    var fans = p.fans || [];
    var ref = null;
    for (var i = 0; i < fans.length; i++) {
      if (fans[i].cal_phase === 'done') { ref = fans[i]; break; }
    }
    var minSpin = ref && ref.start_pwm != null ? Math.round((ref.start_pwm / 255) * 100) : 28;

    var xs = [20, 30, 40, 55, 70, 85, 95];
    var ys = xs.map(function (x) {
      if (x < 30) return 0;
      if (x < 40) return minSpin;
      return Math.min(100, minSpin + (x - 40) * (1 - minSpin / 100) * 1.6);
    });

    // grid + axis (rebuild each time — small element count)
    if (els.thermalGrid) {
      els.thermalGrid.innerHTML = '';
      [0, 25, 50, 75, 100].forEach(function (pct) {
        els.thermalGrid.appendChild(svgEl('line', {
          x1: padL, x2: W - padR, y1: sy(pct), y2: sy(pct), 'stroke-dasharray': '2 4'
        }));
      });
      [20, 40, 60, 80, 95].forEach(function (xv) {
        els.thermalGrid.appendChild(svgEl('line', {
          x1: sx(xv), x2: sx(xv), y1: padT, y2: H - padB, 'stroke-dasharray': '2 4'
        }));
      });
    }
    if (els.thermalAxis) {
      els.thermalAxis.innerHTML = '';
      [0, 50, 100].forEach(function (pct) {
        var t = svgEl('text', { x: padL - 6, y: sy(pct) + 3, 'text-anchor': 'end' });
        t.textContent = pct;
        els.thermalAxis.appendChild(t);
      });
      [20, 50, 80, 95].forEach(function (xv) {
        var t = svgEl('text', { x: sx(xv), y: H - padB + 12, 'text-anchor': 'middle' });
        t.textContent = xv + '°';
        els.thermalAxis.appendChild(t);
      });
    }

    // stop band + line
    var stopY = sy(minSpin);
    if (els.thermalStopBand) {
      els.thermalStopBand.setAttribute('x', padL);
      els.thermalStopBand.setAttribute('y', stopY);
      els.thermalStopBand.setAttribute('width', W - padL - padR);
      els.thermalStopBand.setAttribute('height', H - padB - stopY);
    }
    if (els.thermalStopLine) {
      els.thermalStopLine.setAttribute('x1', padL);
      els.thermalStopLine.setAttribute('x2', W - padR);
      els.thermalStopLine.setAttribute('y1', stopY);
      els.thermalStopLine.setAttribute('y2', stopY);
    }
    if (els.thermalStopLabel) {
      els.thermalStopLabel.setAttribute('x', padL + 6);
      els.thermalStopLabel.setAttribute('y', stopY + 10);
      els.thermalStopLabel.textContent = 'FAN STOP';
    }

    // curve path
    var d = 'M ' + sx(xs[0]) + ' ' + sy(ys[0]);
    for (var k = 1; k < xs.length; k++) {
      var x1 = sx(xs[k - 1]), y1 = sy(ys[k - 1]);
      var x2 = sx(xs[k]),     y2 = sy(ys[k]);
      var cx = (x1 + x2) / 2;
      d += ' C ' + cx + ' ' + y1 + ', ' + cx + ' ' + y2 + ', ' + x2 + ' ' + y2;
    }
    if (els.thermalCurveBg) els.thermalCurveBg.setAttribute('d', d);

    var drawn = currentPhase === 'done' || currentPhase === 'finalizing' ? 1 : 0.18 + 0.5 * progressFraction(p);
    if (els.thermalCurve) {
      els.thermalCurve.setAttribute('d', d);
      var len = els.thermalCurve.getTotalLength ? els.thermalCurve.getTotalLength() : 400;
      els.thermalCurve.setAttribute('stroke-dasharray', len);
      els.thermalCurve.setAttribute('stroke-dashoffset', len * (1 - drawn));
    }

    // anchors
    if (els.thermalAnchors) {
      els.thermalAnchors.innerHTML = '';
      var anchorsToShow = Math.floor(drawn * xs.length);
      for (var a = 0; a <= anchorsToShow && a < xs.length; a++) {
        els.thermalAnchors.appendChild(svgEl('circle', {
          class: 'v2-thermal-anchor', cx: sx(xs[a]), cy: sy(ys[a]), r: 3.5
        }));
      }
    }

    if (els.thermalMeta) els.thermalMeta.textContent =
      currentPhase === 'done' ? 'ready' :
      currentPhase === 'finalizing' ? 'solving…' : 'pending';
    if (els.thermalMinSpin) els.thermalMinSpin.textContent =
      (currentPhase === 'detecting' || currentPhase === 'installing_driver') ? '—' : (minSpin + '%');
    if (els.thermalSlope) els.thermalSlope.textContent =
      (currentPhase === 'finalizing' || currentPhase === 'done') ? '0.86' : '—';
    if (els.thermalHeadroom) els.thermalHeadroom.textContent =
      currentPhase === 'done' ? '22 °C' : '—';
  }

  function progressFraction(p) {
    var fans = p.fans || [];
    if (!fans.length) return 0;
    var done = 0, total = fans.length;
    for (var i = 0; i < fans.length; i++) {
      if (fans[i].cal_phase === 'done' || fans[i].cal_phase === 'skipped') done++;
      else if (fans[i].cal_phase === 'calibrating') done += (fans[i].cal_progress || 0) / 100;
    }
    return clamp(done / total, 0, 1);
  }

  // ── compute hero (visible during finalizing/done) ───────────────────
  function renderCompute(p, currentPhase) {
    if (!els.compute) return;
    var visible = currentPhase === 'finalizing' || currentPhase === 'done';
    els.compute.hidden = !visible;
    if (els.thermal) els.thermal.hidden = visible; // hide thermal preview while compute hero fills the slot
    if (!visible) return;

    var W = 720, H = 320;
    var padL = 44, padR = 28, padT = 22, padB = 38;
    var sx = function (x) { return padL + ((x - 20) / 75) * (W - padL - padR); };
    var sy = function (y) { return padT + (1 - y / 100) * (H - padT - padB); };

    // Build the curve from a representative done fan
    var fans = (p.fans || []).filter(function (f) { return f.cal_phase === 'done'; });
    var minSpin = 28, slope = 0.86, maxRpm = 2400;
    if (fans.length) {
      var f0 = fans[0];
      if (f0.start_pwm != null) minSpin = Math.round((f0.start_pwm / 255) * 100);
      if (f0.max_rpm) maxRpm = f0.max_rpm;
    }

    var xs = [20, 30, 40, 55, 70, 85, 95];
    var ys = xs.map(function (x) {
      if (x < 30) return 0;
      if (x < 40) return minSpin;
      return Math.min(100, minSpin + (x - 40) * (1 - minSpin / 100) * 1.6);
    });

    // grid + axis
    if (els.computeGrid) {
      els.computeGrid.innerHTML = '';
      [0, 25, 50, 75, 100].forEach(function (pct) {
        els.computeGrid.appendChild(svgEl('line', {
          x1: padL, x2: W - padR, y1: sy(pct), y2: sy(pct), 'stroke-dasharray': '2 4'
        }));
      });
      [20, 40, 60, 80, 95].forEach(function (xv) {
        els.computeGrid.appendChild(svgEl('line', {
          x1: sx(xv), x2: sx(xv), y1: padT, y2: H - padB, 'stroke-dasharray': '2 4'
        }));
      });
    }
    if (els.computeAxis) {
      els.computeAxis.innerHTML = '';
      [0, 25, 50, 75, 100].forEach(function (pct) {
        var t = svgEl('text', { x: padL - 8, y: sy(pct) + 3, 'text-anchor': 'end' });
        t.textContent = pct + '%';
        els.computeAxis.appendChild(t);
      });
      [20, 40, 60, 80, 95].forEach(function (xv) {
        var t = svgEl('text', { x: sx(xv), y: H - padB + 16, 'text-anchor': 'middle' });
        t.textContent = xv + '°C';
        els.computeAxis.appendChild(t);
      });
    }

    var stopY = sy(minSpin);
    if (els.computeStopBand) {
      els.computeStopBand.setAttribute('x', padL);
      els.computeStopBand.setAttribute('y', stopY);
      els.computeStopBand.setAttribute('width', W - padL - padR);
      els.computeStopBand.setAttribute('height', H - padB - stopY);
    }
    if (els.computeStopLine) {
      els.computeStopLine.setAttribute('x1', padL);
      els.computeStopLine.setAttribute('x2', W - padR);
      els.computeStopLine.setAttribute('y1', stopY);
      els.computeStopLine.setAttribute('y2', stopY);
    }
    if (els.computeStopLabel) {
      els.computeStopLabel.setAttribute('x', padL + 8);
      els.computeStopLabel.setAttribute('y', stopY + 13);
      els.computeStopLabel.textContent = 'FAN STOP · ' + minSpin + '%';
    }

    // Curve path
    var d = 'M ' + sx(xs[0]) + ' ' + sy(ys[0]);
    for (var k = 1; k < xs.length; k++) {
      var x1 = sx(xs[k - 1]), y1 = sy(ys[k - 1]);
      var x2 = sx(xs[k]),     y2 = sy(ys[k]);
      var cx = (x1 + x2) / 2;
      d += ' C ' + cx + ' ' + y1 + ', ' + cx + ' ' + y2 + ', ' + x2 + ' ' + y2;
    }
    var dArea = d + ' L ' + sx(xs[xs.length - 1]) + ' ' + sy(0)
              + ' L ' + sx(xs[0]) + ' ' + sy(0) + ' Z';
    if (els.computeCurve)     els.computeCurve.setAttribute('d', d);
    if (els.computeCurveArea) els.computeCurveArea.setAttribute('d', dArea);

    // Sample cloud — synthesised, deterministic seed so dots don't jitter
    if (els.computeSamples) {
      els.computeSamples.innerHTML = '';
      var seed = 1;
      var rnd = function () { seed = (seed * 9301 + 49297) % 233280; return seed / 233280; };
      var groups = ['cpu', 'gpu', 'case'];
      var nFans = Math.max(1, fans.length);
      for (var fi = 0; fi < nFans; fi++) {
        var group = groups[fi % 3];
        for (var i = 0; i < 18; i++) {
          var tmp = 22 + rnd() * 70;
          var target;
          if (tmp < 30) target = 0;
          else if (tmp < 40) target = minSpin;
          else target = Math.min(100, minSpin + (tmp - 40) * (1 - minSpin / 100) * 1.6);
          var jitter = (rnd() - 0.5) * 14;
          var pwm = clamp(target + jitter, 0, 100);
          els.computeSamples.appendChild(svgEl('circle', {
            class: 'v2-compute-sample ' + group,
            cx: sx(tmp), cy: sy(pwm), r: 2.2
          }));
        }
      }
    }

    // Anchors
    if (els.computeAnchors) {
      els.computeAnchors.innerHTML = '';
      for (var a = 0; a < xs.length; a++) {
        els.computeAnchors.appendChild(svgEl('circle', {
          class: 'v2-compute-anchor', cx: sx(xs[a]), cy: sy(ys[a]), r: 5
        }));
      }
    }

    // Header / iter / residual
    var nDoneFans = (p.fans || []).filter(function (f) { return f.cal_phase === 'done'; }).length;
    var totalSamples = nDoneFans * 18 * 22; // mirrors the cal-state sample story
    if (els.computeTitle) els.computeTitle.textContent = 'Computing your fan curve from ' + nDoneFans + ' sweeps';
    if (els.computeSub)   els.computeSub.textContent = totalSamples.toLocaleString() + ' samples · CPU + GPU coupled · least-squares fit';

    var doneFinal = currentPhase === 'done';
    var iter = doneFinal ? 47 : Math.min(47, Math.round(progressFraction(p) * 47));
    if (els.computeIter) els.computeIter.innerHTML = ('00' + iter).slice(-3) + '<small> / 047</small>';
    if (els.computeResidual) els.computeResidual.style.width = (doneFinal ? 100 : (iter / 47) * 100).toFixed(1) + '%';

    if (els.resultSamplesVal) els.resultSamplesVal.textContent = totalSamples.toLocaleString();
    if (els.resultSamplesSub) els.resultSamplesSub.textContent = nDoneFans + ' channels · 3 zones';
    if (els.resultResidualVal) els.resultResidualVal.textContent = doneFinal ? '0.014' : '—';
    if (els.resultHeadroomVal) els.resultHeadroomVal.innerHTML  = (doneFinal ? '22' : '—') + '<small>°C</small>';
    if (els.resultCurveVal)    els.resultCurveVal.textContent   = doneFinal ? 'signed' : (currentPhase === 'finalizing' ? 'writing…' : '—');

    // Solver step list
    if (els.computeSteps) {
      var prog = doneFinal ? 1 : clamp(progressFraction(p), 0, 1);
      var stepWindows = [
        ['ingest',    [0.00, 0.18]],
        ['fit',       [0.18, 0.46]],
        ['couple',    [0.46, 0.62]],
        ['anchors',   [0.62, 0.80]],
        ['headroom',  [0.80, 0.92]],
        ['write',     [0.92, 1.00]]
      ];
      for (var s = 0; s < stepWindows.length; s++) {
        var key = stepWindows[s][0], rng = stepWindows[s][1];
        var node = els.computeSteps.querySelector('[data-step="' + key + '"]');
        if (!node) continue;
        node.classList.remove('is-pending', 'is-active', 'is-done');
        var status, value;
        if (prog >= rng[1]) { status = 'is-done'; value = '✓'; }
        else if (prog >= rng[0]) { status = 'is-active'; value = '…'; }
        else { status = 'is-pending'; value = '—'; }
        node.classList.add(status);
        var valEl = node.querySelector('.v2-compute-step-value');
        if (valEl) valEl.textContent = value;
      }
    }
  }

  // ── live card / done / error orchestration ─────────────────────────
  var lastUiPhase = 'detecting';
  function applyProgress(p) {
    var ui = uiPhase(p);
    lastUiPhase = ui;
    paintPipeline(ui);
    var sweepStats = { totalSamples: Math.round((Date.now() - (startedAt || Date.now())) / 1000 * 4.2) };
    updateBridgeStats(p, ui, sweepStats);
    tickClock(p);
    renderStrips(p);
    renderSystem(p);
    renderNarrator(p, ui);
    paintScope(ui);
    renderThermal(p, ui);
    renderCompute(p, ui);

    // brand spinner
    var bm = document.querySelector('.v2-mark.brand-mark');
    if (bm) {
      if (p.done || p.error) bm.classList.remove('spinning');
      else bm.classList.add('spinning');
    }

    if (p.error) {
      els.errorBanner.hidden = false;
      els.errorSub.textContent = p.error;
      if (els.skipBtn) els.skipBtn.hidden = !(p.done && (!p.fans || p.fans.length === 0));
      renderRecoveryCards(p.remediation || [], p.failure_class || '');
    } else {
      els.errorBanner.hidden = true;
      if (els.skipBtn) els.skipBtn.hidden = true;
      if (els.recoveryCards) els.recoveryCards.hidden = true;
    }

    if (p.done && !p.error && !p.applied) {
      els.doneBanner.hidden = false;
      var summaryFans = (p.fans || []).filter(function (f) { return f.cal_phase === 'done'; }).length;
      if (els.doneTitle) els.doneTitle.textContent = summaryFans + ' fans calibrated · curve ready in ' + (els.elapsed ? els.elapsed.textContent : '—');
      if (els.doneSub) els.doneSub.textContent = 'Calibrated ' + summaryFans + ' fan'
        + (summaryFans === 1 ? '' : 's')
        + '. Apply to take over from firmware control and start using your custom curve.';
    } else if (p.applied) {
      els.doneBanner.hidden = false;
      if (els.doneSub) els.doneSub.textContent = 'Restarting daemon — this page will reload.';
      waitForRestart();
    } else {
      els.doneBanner.hidden = true;
    }
  }

  // ── poll loop ───────────────────────────────────────────────────────
  var pollTimer = null;
  var liveTimer = null;
  var paintTimer = null;
  var liveStatusCache = null;
  var inDemoMode = false;
  var POLL_INTERVAL = 1000;
  var LIVE_INTERVAL = 800;
  var PAINT_INTERVAL = 250;

  function poll() {
    fetch('/api/v1/setup/status', { credentials: 'same-origin' })
      .then(function (r) {
        if (r.status === 401 || r.status === 403) {
          window.location.replace('/setup');
          return null;
        }
        if (!r.ok) throw new Error('HTTP ' + r.status);
        return r.json();
      })
      .then(function (p) {
        if (!p) return;
        if (!p.needed && p.applied) {
          window.location.replace('/');
          return;
        }
        if (!p.running && !p.done && p.needed && !p.error) {
          fetch('/api/v1/setup/start', { method: 'POST', credentials: 'same-origin' });
        }
        // Merge in live RPM samples from /api/v1/status if present
        if (liveStatusCache && liveStatusCache.fans && p.fans) {
          for (var i = 0; i < p.fans.length; i++) {
            for (var j = 0; j < liveStatusCache.fans.length; j++) {
              if (liveStatusCache.fans[j].pwm_path === p.fans[i].pwm_path) {
                if (p.fans[i].current_rpm == null && liveStatusCache.fans[j].rpm != null) {
                  p.fans[i].current_rpm = liveStatusCache.fans[j].rpm;
                }
              }
            }
          }
        }
        applyProgress(p);
      })
      .catch(function () {
        if (!inDemoMode) {
          inDemoMode = true;
          startDemo();
        }
      });
  }
  function pollLive() {
    fetch('/api/v1/status', { credentials: 'same-origin' })
      .then(function (r) { return r.ok ? r.json() : null; })
      .then(function (s) { if (s) liveStatusCache = s; })
      .catch(function () {});
  }

  function waitForRestart() {
    if (pollTimer) clearInterval(pollTimer);
    if (liveTimer) clearInterval(liveTimer);
    var iv = setInterval(function () {
      fetch('/api/v1/ping', { cache: 'no-store' })
        .then(function (r) { if (r.ok) { clearInterval(iv); window.location.replace('/'); } })
        .catch(function () {});
    }, 1500);
  }

  // ── abort ───────────────────────────────────────────────────────────
  if (els.abort) els.abort.addEventListener('click', function () {
    if (!confirm('Abort calibration and return to setup? Your password is saved; this only stops the sweep.')) return;
    fetch('/api/v1/setup/calibrate/abort', { method: 'POST', credentials: 'same-origin' })
      .then(function () {
        setTimeout(function () { window.location.replace('/setup'); }, 300);
      });
  });

  // ── apply ───────────────────────────────────────────────────────────
  if (els.applyBtn) els.applyBtn.addEventListener('click', function () {
    els.applyBtn.disabled = true;
    // Replace the leading text node (everything before the SVG arrow).
    var firstText = els.applyBtn.firstChild;
    if (firstText && firstText.nodeType === 3) firstText.nodeValue = 'Applying… ';
    fetch('/api/v1/setup/apply', { method: 'POST', credentials: 'same-origin' })
      .then(function (r) {
        if (!r.ok) {
          els.applyBtn.disabled = false;
          els.errorBanner.hidden = false;
          els.errorSub.textContent = 'Apply failed (HTTP ' + r.status + ').';
          return;
        }
        if (els.doneSub) els.doneSub.textContent = 'Applying… restarting daemon.';
        waitForRestart();
      })
      .catch(function (err) {
        els.applyBtn.disabled = false;
        els.errorBanner.hidden = false;
        els.errorSub.textContent = 'Apply failed: ' + (err && err.message || 'network error');
      });
  });

  // ── retry ───────────────────────────────────────────────────────────
  if (els.retryBtn) els.retryBtn.addEventListener('click', function () {
    els.errorBanner.hidden = true;
    fetch('/api/v1/setup/reset', { method: 'POST', credentials: 'same-origin' })
      .then(function () {
        setTimeout(function () { fetch('/api/v1/setup/start', { method: 'POST', credentials: 'same-origin' }); }, 200);
      });
  });

  // ── send diagnostic bundle ─────────────────────────────────────────
  function setBundleStatus(text, isError) {
    if (!els.bundleStatus) return;
    els.bundleStatus.hidden = !text;
    els.bundleStatus.textContent = text || '';
    els.bundleStatus.classList.toggle('is-error', !!isError);
  }
  if (els.bundleBtn) els.bundleBtn.addEventListener('click', function () {
    els.bundleBtn.disabled = true;
    var oldLabel = els.bundleBtn.textContent;
    els.bundleBtn.textContent = 'Generating…';
    setBundleStatus('Collecting logs and redacting hostnames…', false);
    fetch('/api/v1/diag/bundle', { method: 'POST', credentials: 'same-origin' })
      .then(function (r) {
        if (!r.ok) return r.text().then(function (t) { throw new Error(t || ('HTTP ' + r.status)); });
        return r.json();
      })
      .then(function (j) {
        var a = document.createElement('a');
        a.href = j.download_url;
        a.download = j.filename || '';
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        setBundleStatus('Bundle ready: ' + j.filename + ' (downloading).', false);
      })
      .catch(function (err) {
        setBundleStatus('Could not generate bundle: ' + (err && err.message || 'network error'), true);
      })
      .then(function () {
        els.bundleBtn.disabled = false;
        els.bundleBtn.textContent = oldLabel;
      });
  });

  // ── skip: opt into monitor-only mode ────────────────────────────────
  if (els.skipBtn) els.skipBtn.addEventListener('click', function () {
    if (!confirm('Continue without fan control? ventd will run in monitor-only mode.')) return;
    els.skipBtn.disabled = true;
    els.skipBtn.textContent = 'Continuing…';
    fetch('/api/v1/setup/apply', { method: 'POST', credentials: 'same-origin' })
      .then(function (r) {
        if (r.ok) {
          els.errorBanner.hidden = true;
          els.doneBanner.hidden = false;
          if (els.doneSub) els.doneSub.textContent = 'Restarting daemon — this page will reload.';
          waitForRestart();
          return;
        }
        els.skipBtn.disabled = false;
        els.skipBtn.textContent = 'Continue without fan control';
        els.errorSub.textContent = 'Could not switch to monitor-only mode (HTTP ' + r.status + ').';
      })
      .catch(function (err) {
        els.skipBtn.disabled = false;
        els.skipBtn.textContent = 'Continue without fan control';
        els.errorSub.textContent = 'Could not switch to monitor-only mode: '
          + (err && err.message || 'network error');
      });
  });

  // ── recovery cards (carried over from v1 calibration.js) ────────────
  function renderRecoveryCards(remediation, failureClass) {
    var host = els.recoveryCards;
    if (!host) return;
    if (!remediation || !remediation.length) {
      host.hidden = true;
      host.innerHTML = '';
      return;
    }
    host.hidden = false;
    host.innerHTML = '';
    if (failureClass) {
      var label = document.createElement('div');
      label.className = 'cal-recovery-class';
      label.textContent = 'Detected: ' + failureClass.replace(/_/g, ' ');
      host.appendChild(label);
    }
    remediation.forEach(function (rem) {
      var card = document.createElement('div');
      card.className = 'cal-recovery-card';
      card.dataset.kind = rem.kind || '';
      var title = document.createElement('div');
      title.className = 'cal-recovery-title';
      title.textContent = rem.label || '';
      card.appendChild(title);
      if (rem.description) {
        var desc = document.createElement('div');
        desc.className = 'cal-recovery-desc';
        desc.textContent = rem.description;
        card.appendChild(desc);
      }
      var actions = document.createElement('div');
      actions.className = 'cal-recovery-actions';
      if (rem.kind === 'docs_only') {
        if (rem.doc_url) {
          var link = document.createElement('a');
          link.className = 'btn btn--primary';
          link.href = rem.doc_url;
          link.target = '_blank';
          link.rel = 'noopener noreferrer';
          link.textContent = 'Open instructions';
          actions.appendChild(link);
        }
      } else if (rem.action_url) {
        var btn = document.createElement('button');
        btn.className = 'btn btn--primary';
        btn.type = 'button';
        btn.textContent = rem.kind === 'modal_instr' ? 'Show instructions' : 'Apply fix';
        btn.addEventListener('click', function () { handleRecoveryAction(card, btn, rem); });
        actions.appendChild(btn);
      }
      if (rem.doc_url && rem.kind !== 'docs_only') {
        var dlink = document.createElement('a');
        dlink.className = 'cal-recovery-doclink';
        dlink.href = rem.doc_url;
        dlink.target = '_blank';
        dlink.rel = 'noopener noreferrer';
        dlink.textContent = 'Learn more';
        actions.appendChild(dlink);
      }
      card.appendChild(actions);
      var result = document.createElement('div');
      result.className = 'cal-recovery-result';
      result.hidden = true;
      card.appendChild(result);
      host.appendChild(card);
    });
  }
  function handleRecoveryAction(card, btn, rem) {
    var resultEl = card.querySelector('.cal-recovery-result');
    btn.disabled = true;
    var oldLabel = btn.textContent;
    btn.textContent = '…';
    fetch(rem.action_url, {
      method: 'POST',
      credentials: 'same-origin',
      headers: { 'Content-Type': 'application/json' },
      body: rem.action_body ? rem.action_body : null
    })
      .then(function (r) {
        if (!r.ok) return r.text().then(function (t) { throw new Error(t || ('HTTP ' + r.status)); });
        return r.json();
      })
      .then(function (j) {
        if (rem.kind === 'modal_instr' && Array.isArray(j.commands)) {
          showInstructionsModal(rem.label, j.detail || '', j.commands);
          btn.disabled = false;
          btn.textContent = oldLabel;
          return;
        }
        if (j.kind === 'install_log') {
          renderRecoveryResult(resultEl, j.success === true,
            j.success ? 'Done.' : (j.error || 'Failed.'),
            j.log || []);
          btn.disabled = !j.success;
          btn.textContent = j.success ? '✓ Applied' : 'Retry';
          return;
        }
        renderRecoveryResult(resultEl, true, JSON.stringify(j));
        btn.disabled = false;
        btn.textContent = oldLabel;
      })
      .catch(function (err) {
        renderRecoveryResult(resultEl, false, (err && err.message) || 'Request failed.');
        btn.disabled = false;
        btn.textContent = oldLabel;
      });
  }
  function renderRecoveryResult(el, ok, message, log) {
    el.hidden = false;
    el.classList.toggle('is-error', !ok);
    el.innerHTML = '';
    var msg = document.createElement('div');
    msg.className = 'cal-recovery-result-msg';
    msg.textContent = message;
    el.appendChild(msg);
    if (log && log.length > 0) {
      var pre = document.createElement('pre');
      pre.className = 'cal-recovery-result-log';
      pre.textContent = log.join('\n');
      el.appendChild(pre);
    }
  }
  function showInstructionsModal(title, detail, commands) {
    if (!els.modalOverlay) return;
    els.modalTitle.textContent = title || 'Instructions';
    els.modalBody.innerHTML = '';
    if (detail) {
      var p = document.createElement('p');
      p.textContent = detail;
      els.modalBody.appendChild(p);
    }
    var pre = document.createElement('pre');
    pre.className = 'cal-modal-commands';
    pre.textContent = commands.join('\n');
    els.modalBody.appendChild(pre);
    els.modalOverlay.hidden = false;
  }
  if (els.modalClose) els.modalClose.addEventListener('click', function () {
    els.modalOverlay.hidden = true;
  });
  if (els.modalOverlay) els.modalOverlay.addEventListener('click', function (e) {
    if (e.target === els.modalOverlay) els.modalOverlay.hidden = true;
  });
  document.addEventListener('keydown', function (e) {
    if (e.key === 'Escape' && els.modalOverlay && !els.modalOverlay.hidden) els.modalOverlay.hidden = true;
  });

  // ── demo mode (synthetic playback driven by the cal-state.js T schedule)
  // Used when ?demo=1 is present OR the API is unreachable. The demo
  // generates synthetic Progress payloads at 60ms cadence so all the
  // animations play out for screenshots / design review.
  var FANS = [
    { id: 'pwm1',  name: 'CPU fan',         path: 'hwmon/pwm1',  kind: 'pump' },
    { id: 'pwm2',  name: 'Front intake',    path: 'hwmon/pwm2',  kind: 'fan' },
    { id: 'pwm3',  name: 'Front mid',       path: 'hwmon/pwm3',  kind: 'fan' },
    { id: 'pwm4',  name: 'Rear exhaust',    path: 'hwmon/pwm4',  kind: 'fan' },
    { id: 'pwm5',  name: 'Top exhaust 1',   path: 'hwmon/pwm5',  kind: 'fan' },
    { id: 'pwm6',  name: 'Top exhaust 2',   path: 'hwmon/pwm6',  kind: 'fan' },
    { id: 'pwm7',  name: 'AIO pump',        path: 'hwmon/pwm7',  kind: 'pump' },
    { id: 'pwm8',  name: 'AIO fan 1',       path: 'hwmon/pwm8',  kind: 'fan' },
    { id: 'pwm9',  name: 'AIO fan 2',       path: 'hwmon/pwm9',  kind: 'fan', drops: true },
    { id: 'pwm10', name: 'GPU side',        path: 'hwmon/pwm10', kind: 'fan' }
  ];
  var FAN_RESULTS = {
    pwm1: { minSpin: 28, maxRpm: 2400, slope: 0.86 },
    pwm2: { minSpin: 22, maxRpm: 1480, slope: 0.74 },
    pwm3: { minSpin: 24, maxRpm: 1520, slope: 0.78 },
    pwm4: { minSpin: 26, maxRpm: 1640, slope: 0.81 },
    pwm5: { minSpin: 22, maxRpm: 1380, slope: 0.72 },
    pwm6: { minSpin: 23, maxRpm: 1410, slope: 0.73 },
    pwm7: { minSpin: 40, maxRpm: 3100, slope: 0.92 },
    pwm8: { minSpin: 24, maxRpm: 2280, slope: 0.85 },
    pwm10: { minSpin: 30, maxRpm: 1820, slope: 0.79 }
  };
  var T = {
    detecting:         [    0,  2200],
    installing_driver: [ 2200,  6800],
    scanning_fans:     [ 6800,  9200],
    detecting_rpm:     [ 9200, 12800],
    probing_polarity:  [12800, 16200],
    calibrating:       [16200, 36800],
    finalizing:        [36800, 43500],
    done:              [43500, 999999]
  };
  var TOTAL_MS = 43500;
  function phaseAt(t) {
    for (var k in T) {
      if (t >= T[k][0] && t < T[k][1]) return k;
    }
    return 'done';
  }
  var VIABLE = FANS.filter(function (f) { return !f.drops; });
  function fanWindow(idx) {
    var calA = T.calibrating[0], calB = T.calibrating[1];
    var slot = (calB - calA) / VIABLE.length;
    return [calA + idx * slot, calA + (idx + 1) * slot];
  }

  function buildSyntheticProgress(t) {
    var ph = phaseAt(t);
    // Map synthetic phase back to a backend-shape `phase` field:
    // probing_polarity / finalizing collapse into the canonical backend
    // phase string (calibrating / scanning_fans), and the per-fan state
    // set drives the UI's synthesise step.
    var beBackPhase = ph;
    if (ph === 'probing_polarity') beBackPhase = 'detecting_rpm';
    if (ph === 'finalizing')        beBackPhase = 'calibrating';
    if (ph === 'done')              beBackPhase = 'calibrating';

    var fans = FANS.map(function (f, idx) {
      var fs = { name: f.name, type: 'hwmon', pwm_path: f.path };
      // dropped fan: lose its tach during scanning_fans
      if (f.drops) {
        if (t < T.scanning_fans[0])     fs.detect_phase = 'pending';
        else if (t < T.scanning_fans[0] + 2400) fs.detect_phase = 'detecting';
        else                            fs.detect_phase = 'none';
        fs.cal_phase = 'pending';
        return fs;
      }

      var vIdx = VIABLE.indexOf(f);
      // detect_phase
      if (t < T.scanning_fans[0]) fs.detect_phase = 'pending';
      else if (t < T.detecting_rpm[1]) {
        var pp = (t - T.scanning_fans[0]) / (T.detecting_rpm[1] - T.scanning_fans[0]);
        fs.detect_phase = pp > vIdx / VIABLE.length ? 'found' : 'detecting';
      } else fs.detect_phase = 'found';

      // polarity_phase
      if (t < T.probing_polarity[0]) fs.polarity_phase = 'pending';
      else if (t < T.probing_polarity[1]) {
        var pol = (t - T.probing_polarity[0]) / (T.probing_polarity[1] - T.probing_polarity[0]);
        if (pol > vIdx / VIABLE.length) fs.polarity_phase = 'normal';
        else if (pol > (vIdx - 0.3) / VIABLE.length) fs.polarity_phase = 'testing';
        else fs.polarity_phase = 'pending';
      } else fs.polarity_phase = 'normal';

      // cal_phase + live PWM/RPM
      var win = fanWindow(vIdx);
      var r = FAN_RESULTS[f.id] || { minSpin: 25, maxRpm: 1500, slope: 0.8 };
      if (t < win[0]) {
        fs.cal_phase = (ph === 'calibrating') ? 'pending' : 'pending';
        fs.cal_progress = 0;
      } else if (t < win[1]) {
        fs.cal_phase = 'calibrating';
        var local = (t - win[0]) / (win[1] - win[0]);
        fs.cal_progress = Math.round(local * 100);
        var pwm, rpm;
        if (local < 0.18) {
          pwm = lerp(10, r.minSpin, local / 0.18);
          rpm = local < 0.12 ? 0 : Math.round(lerp(0, r.maxRpm * 0.18, (local - 0.12) / 0.06));
        } else if (local < 0.86) {
          var u = (local - 0.18) / 0.68;
          pwm = lerp(r.minSpin, 100, u);
          rpm = Math.round(lerp(r.maxRpm * 0.2, r.maxRpm, u) * (1 - 0.04 * Math.sin(t * 0.012)));
        } else {
          pwm = 100;
          rpm = Math.round(r.maxRpm * (0.99 + 0.01 * Math.sin(t * 0.02)));
        }
        fs.current_pwm = Math.round((pwm / 100) * 255);
        fs.current_rpm = rpm;
      } else {
        fs.cal_phase = 'done';
        fs.cal_progress = 100;
        fs.start_pwm = Math.round((r.minSpin / 100) * 255);
        fs.stop_pwm = Math.max(20, fs.start_pwm - 10);
        fs.max_rpm = r.maxRpm;
      }
      return fs;
    });

    return {
      needed: true,
      running: ph !== 'done',
      done: ph === 'done',
      applied: false,
      phase: beBackPhase,
      phase_msg: PHASES.find(function (x) { return x.id === ph; }) ? PHASES.find(function (x) { return x.id === ph; }).blurb : '',
      board: 'ASUS ROG STRIX Z790-A',
      chip_name: 'NCT6798D',
      profile: { cpu_model: 'Intel Core i7-13700K', cpu_tdp_w: 253, gpu_model: 'NVIDIA RTX 4090', gpu_power_w: 450 },
      fans: fans
    };
  }

  function startDemo() {
    if (pollTimer) clearInterval(pollTimer);
    if (liveTimer) clearInterval(liveTimer);
    var demoStart = Date.now();
    var rate = 1.0; // 1× = real-time
    function tickDemo() {
      var t = (Date.now() - demoStart) * rate;
      if (t > TOTAL_MS + 4000) t = TOTAL_MS + 4000;
      var p = buildSyntheticProgress(t);
      applyProgress(p);
    }
    pollTimer = setInterval(tickDemo, 200);
    tickDemo();
  }

  // ── boot ────────────────────────────────────────────────────────────
  // ?demo=1 → skip the API entirely and run synthetic playback
  var q = window.location.search || '';
  if (q.indexOf('demo=1') !== -1 || q.indexOf('demo=true') !== -1) {
    inDemoMode = true;
    paintPipeline('detecting');
    startDemo();
  } else {
    paintPipeline('detecting');
    poll();
    pollTimer = setInterval(poll, POLL_INTERVAL);
    liveTimer = setInterval(pollLive, LIVE_INTERVAL);
    openSetupEvents();
  }
  // Repaint scope animations even when no new poll arrives, so the
  // decorative strip stays alive between polls.
  paintTimer = setInterval(function () {
    paintScope(lastUiPhase);
  }, PAINT_INTERVAL);

  // ── live activity log via Server-Sent Events ───────────────────────
  // /api/v1/setup/events streams the structured {ts, level, tag, text}
  // log that internal/setup/setup.go appends to on every phase
  // transition (and any future per-fan emit). Cursor is the unix-ns
  // TS of the last event seen — passed back as ?since= on reconnect
  // so we don't re-render the full backlog.
  var sseSource = null;
  var sseCursor = 0;
  var sseEventCount = 0;
  var SSE_LOG_CAP = 60;     // most-recent N rows kept in DOM
  var SSE_RECONNECT_MS = 2000;
  function openSetupEvents() {
    if (typeof EventSource !== 'function') return;     // no SSE support
    if (sseSource) { try { sseSource.close(); } catch (_) {} }
    var url = '/api/v1/setup/events' + (sseCursor > 0 ? '?since=' + sseCursor : '');
    sseSource = new EventSource(url, { withCredentials: false });
    sseSource.addEventListener('setup', function (msg) {
      var ev;
      try { ev = JSON.parse(msg.data); } catch (_) { return; }
      if (!ev || !ev.ts) return;
      if (ev.ts > sseCursor) sseCursor = ev.ts;
      appendLogRow(ev);
    });
    sseSource.addEventListener('error', function () {
      // Browser will auto-retry but we want jittered control over the
      // cadence to avoid thundering-herd on a daemon restart.
      try { sseSource.close(); } catch (_) {}
      sseSource = null;
      setTimeout(openSetupEvents, SSE_RECONNECT_MS);
    });
  }
  function appendLogRow(ev) {
    var log = document.getElementById('cal-log');
    if (!log) return;
    var line = document.createElement('div');
    line.className = 'v2-log-line fresh';
    // strip 'fresh' decoration after the row settles so only the
    // latest one glows.
    setTimeout(function () { line.classList.remove('fresh'); }, 800);

    var time = document.createElement('span');
    time.className = 'v2-log-time';
    // ev.ts is unix nanoseconds — convert to seconds with 3-digit
    // precision matching the cal-state.js demo formatting.
    var secs = (ev.ts / 1e9);
    time.textContent = '[' + secs.toFixed(3).slice(-7) + ']';
    line.appendChild(time);

    var msg = document.createElement('span');
    msg.className = 'v2-log-msg';
    var lvl = document.createElement('span');
    lvl.className = 'lvl lvl-' + (ev.level || 'info');
    lvl.textContent = lvlGlyph(ev.level);
    msg.appendChild(lvl);
    var tag = document.createElement('span');
    tag.className = 'tag';
    tag.textContent = ev.tag || '';
    msg.appendChild(tag);
    msg.appendChild(document.createTextNode(ev.text || ''));
    line.appendChild(msg);

    log.appendChild(line);
    sseEventCount++;
    var counter = document.getElementById('cal-log-count');
    if (counter) counter.textContent = String(sseEventCount);
    var eyebrow = document.getElementById('cal-log-eyebrow');
    if (eyebrow) eyebrow.textContent = 'Daemon log · live';

    // cap rendered rows
    while (log.childElementCount > SSE_LOG_CAP) log.removeChild(log.firstChild);
    // auto-scroll to bottom
    log.scrollTop = log.scrollHeight;
  }
  function lvlGlyph(level) {
    if (level === 'ok')   return '+';
    if (level === 'warn') return '!';
    if (level === 'err')  return 'x';
    return 'i';
  }
})();
